//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.ReferenciaDePedido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/DomainLoja")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecoProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Teste.ReferenciaDePedido.Pedido pedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaProduto {
            get {
                return this.CategoriaProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaProdutoField, value) != true)) {
                    this.CategoriaProdutoField = value;
                    this.RaisePropertyChanged("CategoriaProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemProduto {
            get {
                return this.ImagemProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemProdutoField, value) != true)) {
                    this.ImagemProdutoField = value;
                    this.RaisePropertyChanged("ImagemProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto {
            get {
                return this.NomeProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeProdutoField, value) != true)) {
                    this.NomeProdutoField = value;
                    this.RaisePropertyChanged("NomeProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrecoProduto {
            get {
                return this.PrecoProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecoProdutoField, value) != true)) {
                    this.PrecoProdutoField = value;
                    this.RaisePropertyChanged("PrecoProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantidadeProduto {
            get {
                return this.QuantidadeProdutoField;
            }
            set {
                if ((this.QuantidadeProdutoField.Equals(value) != true)) {
                    this.QuantidadeProdutoField = value;
                    this.RaisePropertyChanged("QuantidadeProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProduto {
            get {
                return this.idProdutoField;
            }
            set {
                if ((this.idProdutoField.Equals(value) != true)) {
                    this.idProdutoField = value;
                    this.RaisePropertyChanged("idProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Teste.ReferenciaDePedido.Pedido pedido {
            get {
                return this.pedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.pedidoField, value) != true)) {
                    this.pedidoField = value;
                    this.RaisePropertyChanged("pedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/DomainLoja")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PedidoEnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PedidoSalvoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Teste.ReferenciaDePedido.Produto[] ProdutosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PedidoEnviado {
            get {
                return this.PedidoEnviadoField;
            }
            set {
                if ((this.PedidoEnviadoField.Equals(value) != true)) {
                    this.PedidoEnviadoField = value;
                    this.RaisePropertyChanged("PedidoEnviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PedidoSalvo {
            get {
                return this.PedidoSalvoField;
            }
            set {
                if ((this.PedidoSalvoField.Equals(value) != true)) {
                    this.PedidoSalvoField = value;
                    this.RaisePropertyChanged("PedidoSalvo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Teste.ReferenciaDePedido.Produto[] Produtos {
            get {
                return this.ProdutosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutosField, value) != true)) {
                    this.ProdutosField = value;
                    this.RaisePropertyChanged("Produtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPedido {
            get {
                return this.idPedidoField;
            }
            set {
                if ((this.idPedidoField.Equals(value) != true)) {
                    this.idPedidoField = value;
                    this.RaisePropertyChanged("idPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoViewModel", Namespace="http://schemas.datacontract.org/2004/07/GerenciarPedido.Modelo")]
    [System.SerializableAttribute()]
    public partial class PedidoViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PedidoEnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PedidoSalvoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Teste.ReferenciaDePedido.Produto[] ProdutosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PedidoEnviado {
            get {
                return this.PedidoEnviadoField;
            }
            set {
                if ((this.PedidoEnviadoField.Equals(value) != true)) {
                    this.PedidoEnviadoField = value;
                    this.RaisePropertyChanged("PedidoEnviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PedidoSalvo {
            get {
                return this.PedidoSalvoField;
            }
            set {
                if ((this.PedidoSalvoField.Equals(value) != true)) {
                    this.PedidoSalvoField = value;
                    this.RaisePropertyChanged("PedidoSalvo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Teste.ReferenciaDePedido.Produto[] Produtos {
            get {
                return this.ProdutosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutosField, value) != true)) {
                    this.ProdutosField = value;
                    this.RaisePropertyChanged("Produtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPedido {
            get {
                return this.idPedidoField;
            }
            set {
                if ((this.idPedidoField.Equals(value) != true)) {
                    this.idPedidoField = value;
                    this.RaisePropertyChanged("idPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:52679/v2", ConfigurationName="ReferenciaDePedido.PedidoComposto")]
    public interface PedidoComposto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/SalvarPedido", ReplyAction="http://localhost:52679/v2/PedidoComposto/SalvarPedidoResponse")]
        string SalvarPedido(Teste.ReferenciaDePedido.Produto[] ListaProdutos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/SalvarPedido", ReplyAction="http://localhost:52679/v2/PedidoComposto/SalvarPedidoResponse")]
        System.Threading.Tasks.Task<string> SalvarPedidoAsync(Teste.ReferenciaDePedido.Produto[] ListaProdutos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/ProximoPedido", ReplyAction="http://localhost:52679/v2/PedidoComposto/ProximoPedidoResponse")]
        Teste.ReferenciaDePedido.PedidoViewModel ProximoPedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/ProximoPedido", ReplyAction="http://localhost:52679/v2/PedidoComposto/ProximoPedidoResponse")]
        System.Threading.Tasks.Task<Teste.ReferenciaDePedido.PedidoViewModel> ProximoPedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/PedidoSalvo", ReplyAction="http://localhost:52679/v2/PedidoComposto/PedidoSalvoResponse")]
        bool PedidoSalvo(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/PedidoSalvo", ReplyAction="http://localhost:52679/v2/PedidoComposto/PedidoSalvoResponse")]
        System.Threading.Tasks.Task<bool> PedidoSalvoAsync(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/PedidoEnviado", ReplyAction="http://localhost:52679/v2/PedidoComposto/PedidoEnviadoResponse")]
        bool PedidoEnviado(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v2/PedidoComposto/PedidoEnviado", ReplyAction="http://localhost:52679/v2/PedidoComposto/PedidoEnviadoResponse")]
        System.Threading.Tasks.Task<bool> PedidoEnviadoAsync(int idPedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidoCompostoChannel : Teste.ReferenciaDePedido.PedidoComposto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoCompostoClient : System.ServiceModel.ClientBase<Teste.ReferenciaDePedido.PedidoComposto>, Teste.ReferenciaDePedido.PedidoComposto {
        
        public PedidoCompostoClient() {
        }
        
        public PedidoCompostoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoCompostoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoCompostoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoCompostoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SalvarPedido(Teste.ReferenciaDePedido.Produto[] ListaProdutos) {
            return base.Channel.SalvarPedido(ListaProdutos);
        }
        
        public System.Threading.Tasks.Task<string> SalvarPedidoAsync(Teste.ReferenciaDePedido.Produto[] ListaProdutos) {
            return base.Channel.SalvarPedidoAsync(ListaProdutos);
        }
        
        public Teste.ReferenciaDePedido.PedidoViewModel ProximoPedido() {
            return base.Channel.ProximoPedido();
        }
        
        public System.Threading.Tasks.Task<Teste.ReferenciaDePedido.PedidoViewModel> ProximoPedidoAsync() {
            return base.Channel.ProximoPedidoAsync();
        }
        
        public bool PedidoSalvo(int idPedido) {
            return base.Channel.PedidoSalvo(idPedido);
        }
        
        public System.Threading.Tasks.Task<bool> PedidoSalvoAsync(int idPedido) {
            return base.Channel.PedidoSalvoAsync(idPedido);
        }
        
        public bool PedidoEnviado(int idPedido) {
            return base.Channel.PedidoEnviado(idPedido);
        }
        
        public System.Threading.Tasks.Task<bool> PedidoEnviadoAsync(int idPedido) {
            return base.Channel.PedidoEnviadoAsync(idPedido);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:52679/v1", ConfigurationName="ReferenciaDePedido.PedidoSimples")]
    public interface PedidoSimples {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/SalvarPedido", ReplyAction="http://localhost:52679/v1/PedidoSimples/SalvarPedidoResponse")]
        string SalvarPedido(Teste.ReferenciaDePedido.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/SalvarPedido", ReplyAction="http://localhost:52679/v1/PedidoSimples/SalvarPedidoResponse")]
        System.Threading.Tasks.Task<string> SalvarPedidoAsync(Teste.ReferenciaDePedido.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/ProximoPedido", ReplyAction="http://localhost:52679/v1/PedidoSimples/ProximoPedidoResponse")]
        Teste.ReferenciaDePedido.PedidoViewModel ProximoPedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/ProximoPedido", ReplyAction="http://localhost:52679/v1/PedidoSimples/ProximoPedidoResponse")]
        System.Threading.Tasks.Task<Teste.ReferenciaDePedido.PedidoViewModel> ProximoPedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/PedidoSalvo", ReplyAction="http://localhost:52679/v1/PedidoSimples/PedidoSalvoResponse")]
        bool PedidoSalvo(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/PedidoSalvo", ReplyAction="http://localhost:52679/v1/PedidoSimples/PedidoSalvoResponse")]
        System.Threading.Tasks.Task<bool> PedidoSalvoAsync(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/PedidoEnviado", ReplyAction="http://localhost:52679/v1/PedidoSimples/PedidoEnviadoResponse")]
        bool PedidoEnviado(int idPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:52679/v1/PedidoSimples/PedidoEnviado", ReplyAction="http://localhost:52679/v1/PedidoSimples/PedidoEnviadoResponse")]
        System.Threading.Tasks.Task<bool> PedidoEnviadoAsync(int idPedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidoSimplesChannel : Teste.ReferenciaDePedido.PedidoSimples, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoSimplesClient : System.ServiceModel.ClientBase<Teste.ReferenciaDePedido.PedidoSimples>, Teste.ReferenciaDePedido.PedidoSimples {
        
        public PedidoSimplesClient() {
        }
        
        public PedidoSimplesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoSimplesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoSimplesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoSimplesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SalvarPedido(Teste.ReferenciaDePedido.Produto produto) {
            return base.Channel.SalvarPedido(produto);
        }
        
        public System.Threading.Tasks.Task<string> SalvarPedidoAsync(Teste.ReferenciaDePedido.Produto produto) {
            return base.Channel.SalvarPedidoAsync(produto);
        }
        
        public Teste.ReferenciaDePedido.PedidoViewModel ProximoPedido() {
            return base.Channel.ProximoPedido();
        }
        
        public System.Threading.Tasks.Task<Teste.ReferenciaDePedido.PedidoViewModel> ProximoPedidoAsync() {
            return base.Channel.ProximoPedidoAsync();
        }
        
        public bool PedidoSalvo(int idPedido) {
            return base.Channel.PedidoSalvo(idPedido);
        }
        
        public System.Threading.Tasks.Task<bool> PedidoSalvoAsync(int idPedido) {
            return base.Channel.PedidoSalvoAsync(idPedido);
        }
        
        public bool PedidoEnviado(int idPedido) {
            return base.Channel.PedidoEnviado(idPedido);
        }
        
        public System.Threading.Tasks.Task<bool> PedidoEnviadoAsync(int idPedido) {
            return base.Channel.PedidoEnviadoAsync(idPedido);
        }
    }
}
